Repository osc-5/openSourceTeam5, pull requests merged in 2020-09, with the labels that each got.

#2 [#1] feat - 스켈레톤 코드 작성
  index.html
Labels: front-end

#5 메인(기본) 페이지 코드 작성
  css/main_page.css
  index.html
  main_page.html
Labels: front-end

#7 calendar page 스켈레톤 코드 작성
  calendar_page.html
  conference.json
  css/calendar_page.css
  parsing.js
Labels: front-end

#10 캘린더 페이지 데이터 연결
  .gitignore
  calendar.js
  calendar_page.html
  conference.js
  css/calendar_page.css
  html_generator.js
  main_page.html
Labels: front-end

#12 readme 파일 초기버전 작성
  .gitignore
  README.md
Labels: documentation

#15 폴더 구조를 변경
  html/calendar_page.html
  html/main_page.html
  js/calendar.js
  js/datas/conference.js
  js/utils/html_generator.js
  js/utils/parsing.js
Labels: front-end

#20 frontend_roadmap입니다.
  first.html
  style.css
Labels: front-end, setting

#23 폴더 구조 변경 및 관련 파일 수정
  css/calendar.css
  css/main.css
  css/roadmap.css
  html/calendar.html
  html/calendar_page.html
  html/main.html
  html/roadmap.html
Labels: front-end

#27 로드맵 페이지 스타일 수정 및 요소 추가
  css/roadmap.css
  html/roadmap.html
Labels: enhancement

#28 코드프리징 #1
  .gitignore
  README.md
  css/calendar.css
  css/main.css
  css/roadmap.css
  html/calendar.html
  html/main.html
  html/roadmap.html
  index.html
  js/calendar.js
  js/datas/conference.js
  js/utils/html_generator.js
  js/utils/parsing.js
Labels: release

#29 index.html 이 기본으로 나오도록 수정
  css/index.css
  index.html
Labels: setting

#30 코드프리징 #2
  README.md
  css/index.css
  index.html
Labels: release

#32 모든 페이지에 상단메뉴 추가
  css/index.css
  html/calendar.html
  html/roadmap.html
  index.html
Labels: front-end

#34 로드맵 css 깨지는거 고침
  css/index.css
  css/roadmap.css
  html/roadmap.html
  index.html
Labels: front-end

#36 화면 깨짐 고침
  css/roadmap.css
  html/roadmap.html
Labels: bug

#37 코드프리징 #3
  css/index.css
  css/roadmap.css
  html/calendar.html
  html/roadmap.html
  index.html
Labels: release

#39 github icon 클릭시 이벤트 추가
  .DS_Store
  css/calendar.css
  css/roadmap.css
  html/roadmap.html
  img/github-logo.png
Labels: front-end

#40 코드프리징#4
  .DS_Store
  css/calendar.css
  css/roadmap.css
  html/roadmap.html
  img/github-logo.png
Labels: release
